language: node_js
node_js:
  - "12"


sudo: "required"
services:
  - docker

script:
  - npm run lint
  - npm run compile
  - npm run test

deploy:
  provider: script
  script: publish_dockerhub.sh
  on:
    tags: true
