version: '2.3'
services:
  rts:    #xrchat-realtime-server
    build: 
      context: ../xrchat-realtime-server
    image: xrchat-realtime-server
    restart: always

  server:
    build: 
      context: ../xrchat-server
    image: xrchat-server
    restart: always
    environment:
      PORT: 3030
      MYSQL_URL: mysql://server:password@db:3306/xrchat # take care, db not localhost, because compose uses an intenal DNS
    ports:
      - '3030:3030'
    depends_on: 
      - db
  
  client:
    build: 
      context: ../xrchat-client
      args: 
        API_SERVER_URL: http://localhost:3030
    image: xrchat-client
    restart: always
    ports:
      - '3000:3000'
 
  # DB Server
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xrchat-root-pa$$w0rd
      MYSQL_DATABASE: xrchat
      MYSQL_USER: server
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
 

  # lets you view the database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
