rbac:
  create: true

controller:
  config:
    ssl-redirect: "true" # we use `special` port to control ssl redirection 
    # server-snippet: |
    #   listen 8000;
    #   if ( $server_port = 80 ) {
    #      return 308 https://$host$request_uri;
    #   }
  containerPort:
    http: 80
    https: 443
    # special: 8000
  service:
    targetPorts:
      http: http
      https: http
    annotations:
      # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:991629384580:certificate/c9e8552f-f79e-4ff2-8026-85310f2ac922"
      # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
