
version: '2.3'
services:
  local-file-server:
    build: 
      context: ../
      dockerfile: FileServerDockerFile
    container_name: http-server
    ports:
      - '8642:8642'
    volumes:
      - ../packages/server/upload:/usr/app/upload:z
    user: $USER