{{- if .Values.apiServer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrchat.apiServer.fullname" . }}
  labels:
    {{- include "xrchat.apiServer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
    - port: {{ .Values.apiServer.service.port }}
      targetPort: {{ .Values.apiServer.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "xrchat.apiServer.selectorLabels" . | nindent 4 }}
{{- end -}}
