{{- if .Values.apiServer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xrchat.apiServer.fullname" . }}
  labels:
    {{- include "xrchat.apiServer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "xrchat.apiServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xrchat.apiServer.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api-server-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.apiServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xrchat.apiServer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.apiServer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.apiServer.securityContext | nindent 12 }}
          image: "{{ .Values.apiServer.image.repository }}:{{ .Values.apiServer.image.tag }}"
          imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "xrchat.apiServer.fullname" . }}
                optional: true
          env:
            - name: KUBERNETES
              value: "true"
            - name: MYSQL_USER
              value: {{ .Values.mariadb.db.user }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.db.name }}
            - name: MYSQL_PASSWORD
              {{- if not .Values.mariadb.enabled }}
              value: {{ .Values.mariadb.db.password }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.existingSecret }}
                  name: {{ .Values.mariadb.existingSecret }}
                  {{- else }}
                  name: {{ template "xrchat.mariadb.fullname" . }}
                  {{- end }} 
                  key: mariadb-password
              {{- end }}
            - name: MYSQL_HOST
              value: {{ template "xrchat.mariadb.host" . }}
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.apiServer.resources | nindent 12 }}
      {{- with .Values.apiServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.apiServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.apiServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
