apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "xrchat.client.fullname" . }}
  labels:
    {{- include "xrchat.client.labels" . | nindent 4 }}
data:
{{- if .Values.client.extraEnv }}
{{ toYaml .Values.client.extraEnv | indent 2 }}
{{- end }}
