{{- if and .Values.mediaServer.enabled .Values.mediaServer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xrchat.mediaServer.serviceAccountName" . }}
  labels:
    {{- include "xrchat.mediaServer.labels" . | nindent 4 }}
  {{- with .Values.mediaServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
